export { default as Brand } from './img/brand.png';
export { default as HomeFooter } from './img/footer.png';
export { default as HomeHero } from './img/home-photo-1.png';
export { default as HomeServices1 } from './img/home-photo-2.png';
export { default as HomeServices2 } from './img/home-photo-3.png';
export { default as HomeServices3 } from './img/home-photo-4.png'
export { default as CloseIcon } from './svg/close.svg?react';
export { default as HamburgerIcon } from './svg/hamburger.svg?react';
export { default as TiktokIcon } from './svg/tiktok.svg?react';
export { default as TiktokIconBlack } from './svg/tiktokblack.svg?react';
export { default as FacebookIcon } from './svg/facebook.svg?react';
export { default as WhatsappIcon } from './svg/whatsapp.svg?react';
export { default as LocationIcon } from './svg/location.svg?react';
export { default as ImageDecoTopIcon } from './svg/img-deco-top.svg?react';
export { default as ImageDecoDownIcon } from './svg/img-deco-bottom.svg?react';