// PNG
export { default as Brand } from './img/brand.png';
export { default as Footer } from './img/footer.png';
export { default as HomeHero } from './img/home-photo-1.png';
export { default as HomeAboutUs } from './img/home-photo-2.png';
export { default as HomeWhatWeDo } from './img/home-photo-3.png';
export { default as HomeCenterFiv } from './img/home-photo-4.png';
export { default as HomeServices1 } from './img/home-services-1.png';
export { default as HomeServices2 } from './img/home-services-2.png';
export { default as HomeServices3 } from './img/home-services-3.png';
export { default as HomeServices4 } from './img/home-services-4.png';
export { default as HomeServices5 } from './img/home-services-5.png';
export { default as HomeServices6 } from './img/home-services-6.png';
export { default as ContactBanner } from './img/contact-banner.png';
export { default as ContactHero } from './img/contact-photo-1.png';
export { default as ContactMap } from './img/contact-photo-2.png';
export { default as AboutBanner } from './img/home-photo-3.png';
export { default as AboutHero } from './img/home-photo-3.png';
export { default as AboutDoctor1 } from './img/about-photo-1.png';
export { default as AboutDoctor2 } from './img/about-photo-2.png';
export { default as AboutDoctor3 } from './img/about-photo-3.png';
export { default as ServicesBanner } from './img/services-banner.png';
export { default as ServicesDetail } from './img/services-photo-1.png';
export { default as LabTestRequest } from './img/contact-photo-1.png';
export { default as LabFormBanner } from './img/lab-photo-1.png';

// SVG
export { default as FacebookIcon } from './svg/facebook.svg?react';
export { default as TiktokIcon } from './svg/tiktok.svg?react';
export { default as WhatsappIcon } from './svg/whatsapp.svg?react';
export { default as EmailIcon } from './svg/email.svg?react';
export { default as HamburgerIcon } from './svg/hamburger.svg?react';
export { default as CloseIcon } from './svg/close.svg?react';
export { default as PhoneIcon } from './svg/phone.svg?react';
export { default as PhoneCallingIcon } from './svg/phone-calling.svg?react';
export { default as ImageDeco} from './svg/img-deco.svg?react';
export { default as CheckBoxFilledIcon } from './svg/checkbox-filled.svg?react';
export { default as CheckBoxWhiteIcon } from './svg/checkbox-filled-white.svg?react';
export { default as LocationIcon } from './svg/location.svg?react';
export { default as MediaPlayIcon } from './svg/media-play.svg?react';
export { default as ArrowRightIcon } from './svg/arrow-right.svg?react';
